; 用 utf-8 编码保存, rime_path位置不能变，且只能在第三行，= 两边空格一定要有，一般只用改d 后的路径

[rime_path]
; d 是默认路径
d_rime_path = D:\Program_Files\Rime

[dict_path]
; 路径双反斜杠
d_dict_path = D:\\Program_Files\\RimeUserData\\wubi.dict.yaml

[udict_path]
d_udict_path = D:\\Program_Files\\RimeUserData\\wubi_user.dict.yaml

[pydict_path]
d_pydict_path = D:\\Program_Files\\RimeUserData\\pinyin_simp.dict.yaml

[lua_path]
d_lua_path = D:\\Program_Files\\RimeUserData\\lua\\primary_character_filter.lua

[start_line]
; 第一个词条所在的行数，因为从 0 开始，所以下面为实际行数减一
wubi = 32
en = 18
